"""Rename count_normal to count_soso in routes table

Revision ID: 5ee6b9778050
Revises: 3ef452efa3fd
Create Date: 2025-10-25 16:27:22.407120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '5ee6b9778050'
down_revision: Union[str, Sequence[str], None] = '3ef452efa3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('count_normal', new_column_name='count_soso', existing_type=sa.Integer(), nullable=False, server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.alter_column('count_soso', new_column_name='count_normal', existing_type=sa.Integer(), nullable=False, server_default=sa.text('0'))
    # ### end Alembic commands ###
